version: "3.4"
services:
  nsl-homeassistant:
    container_name: nsl-homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config/
    network_mode: "host"
    environment:
      - TZ=Asia/Kolkata
    tty: true
    privileged: true
    

    
      
