version: "3.4"
services:
  nsl-homeassistant:
    container_name: nsl-homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config/
    ports:
      - "8123:8123"
    labels:
      dev.okteto.com/private: "true"
    environment:
      - TZ=Asia/Kolkata
    tty: true
    privileged: true
    

    
      
